CREATE TABLE IF NOT EXISTS sessions (
	id INTEGER PRIMARY KEY AUTOINCREMENT, 
	sessionUUID TEXT NOT NULL UNIQUE, 
	userID INTEGER NOT NULL UNIQUE, 
	username TEXT NOT NULL,
	FOREIGN KEY (userID) REFERENCES users(id) ON DELETE CASCADE
);